### ISSUE TITLE
Use Resolvers In Policies

### ISSUE THREAD

**Issue by dyoder** [dashkite/enchant#8]
The idea would be to set up resolvers like we do in Runes and reference them from conditions or actions, like so:

```yaml
- name: resource
  resolvers: [ foo ]
  value:
      name: foo
      value: ${ foo }
```

This solves the awkwardness associated with needing context to evaluate a condition.
